### ISSUE TITLE
`format` option not working after upgrade to eslint 2.2.0

### ISSUE THREAD

**Issue by cowchimp** [sindresorhus/grunt-eslint#109]
Hi.
Thanks for this great grunt plugin.

Passing the `format` option to the eslint task results in error
`Warning: Cannot read property 'cwd' of undefined Use --force to continue.`
(it worked fine with eslint 1.10.3 and grunt-eslint 17.3.1)

I'm pretty sure this is related to a change eslint made here recently eslint/eslint#4472.
But I'm not sure if this is an issue with `eslint` itself or `grunt-eslint` calling `eslint` in a bad way.

The value I'm passing to the `format` option is a string which describes the path of the formatter I want to use.
As you can see what grunt-eslint does with this is pass it to [`eslint.CLIEngine.getFormatter(opts.format)`](https://github.com/sindresorhus/grunt-eslint/blob/850ebc19c325b550e576207ff37ffbe99faa3d02/tasks/eslint.js#L27)
Because `CLIEngine` is never instantiated it throws an error, because it references `this.options` within and `this.options` is undefined (`options` is set with `defaultOptions` in the constructor).
I'm referring to this line [`formatterPath = path.resolve(this.options.cwd, format)`](https://github.com/eslint/eslint/blob/2bd57b6bbd11b23fdec65dc11c691f74c6a8db75/lib/cli-engine.js#L407)
(in previous version of eslint it didn't reference `this.options.cwd` but rather `process.cwd()` and that's why it was not an issue beforehand)

WDYT?
Thanks!

**Comment by sindresorhus** [comment]
> Because CLIEngine is never instantiated it throws an error, because it references this.options within and this.options is undefined (options is set with defaultOptions in the constructor).

Sounds like a ESLint bug. That method is [documented](http://eslint.org/docs/developer-guide/nodejs-api#getformatter) as also being available as a static method:

> Note: Also available as a static function on CLIEngine.

**Comment by cowchimp** [comment]
Great. Will open an issue there. Thanks a lot!

**Comment by cowchimp** [comment]
@sindresorhus looks like you got them to expose it as static :-) eslint/eslint#3239

**Comment by cowchimp** [comment]
Hi. Bug was fixed upstream.
Can you please upgrade to the latest version of eslint?
http://eslint.org/blog/2016/03/eslint-v2.3.0-released

**Comment by sindresorhus** [comment]
Just reinstall this plugin and you'll get it automatically.

https://nodesource.com/blog/semver-tilde-and-caret
