### ISSUE TITLE
Define `globals` in the options

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/grunt-eslint#110]
I am trying to replace ESLint to a project, and I want to add certain `globals` to only one of my targets (meaning, I can't put it in my .eslintrc), but couldn't figure out how.

I have this that is working.
```js
{
        src: [
            'some/**/*.js',
            'files/**/*.js'
        ]
}
```
Now, I don't know where to put the `globals` (or `global`?) key. If I add it next to `src`, it gets ignored, and if I put it into an `options` object, I get `undefined is not a function`.
Thanks!

**Comment by sindresorhus** [comment]
```js
{
    yourTarget: {
        options: {
            globals: ['sindre', 'unicorns']
        },
        src: [
            'some/**/*.js',
            'files/**/*.js'
        ]
    }
}
```

See the linked ESLint docs for what options you can use: http://eslint.org/docs/developer-guide/nodejs-api#cliengine

**Comment by jfmengels** [comment]
Ok, now I don't remember how I tried it before (I thought I did what you said), but now it seems to work anyway... thanks!
