### ISSUE TITLE
"extends": "google"

### ISSUE THREAD

**Issue by davidmaxwaterman** [sindresorhus/grunt-eslint#112]
I'm having trouble getting this option set within my Gruntfile.js. It works if I set it in my .eslintrc file, but not the Gruntfile.
I guess I'm missing something - any ideas?

In my .eslintrc files, I have :

```
{
  "extends": "google"
}
```

and in my Gruntfile.js, I'm trying :

```
    eslint: {
      options: {
        "extends": "google"
      },
      target: ['app/js/*.js']
    },
```

With the eslintrc file, I get `✖ 1224 problems (1148 errors, 76 warnings)`, but with just the Gruntfile.js, I get no errors.

**Comment by sindresorhus** [comment]
There's no `extends` option for this task.
