### ISSUE TITLE
Warning: Task "eslint:target" failed. Use --force to continue.

### ISSUE THREAD

**Issue by jonathandion** [sindresorhus/grunt-eslint#113]
Every time I run the command my grunt task ends with : 
`
✖ 10 problems (9 errors, 1 warning)
Warning: Task "eslint:target" failed. Use --force to continue.
`

But it's look like my target is working due of the problems and the warning.

What i'm doing wrong ? 

Thanks.

**Comment by sindresorhus** [comment]
That's just how grunt shows that the task failed due to lint problems.
