### ISSUE TITLE
Make eslint a peer dependency

### ISSUE THREAD

**Issue by lukeapage** [sindresorhus/grunt-eslint#116]
I would like to control when I upgrade eslint, not have it enforced upon me when I do an install.

**Comment by kevva** [comment]
Why? Mostly `peerDependencies` is a nightmare.

**Comment by sindresorhus** [comment]
Then lock down this dependency. We do new releases for every ESLint major version bump.

**Comment by sindresorhus** [comment]
You can also specify ESLint as a dependency and if you use npm v3 it will be deduped.
