### ISSUE TITLE
Add --fix option?

### ISSUE THREAD

**Issue by pertrai1** [sindresorhus/grunt-eslint#117]
Is there a way to have an option to pass in `--fix` so those rules that can be fixed will be fixed just like one would when passing that in the CLI? That would help very much with some of the rules we need to have automatically fixed like linebreak-style since some of our developers work on windows machine and some on unix.

Thank you

**Comment by kevva** [comment]
Adding `fix: true` to your options should do it.

**Comment by pertrai1** [comment]
Awesome. Thanks @kevva

**Comment by markmhx** [comment]
I'd recommend adding guidance for this option to the README since it took googling to get here and learn this.
