### ISSUE TITLE
Grunt 1.0

### ISSUE THREAD

**Issue by YaManicKill** [sindresorhus/grunt-eslint#120]
Could you update to use grunt 1.0 on your peer dependency. Currently we get:

The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!  
Peer grunt-eslint@18.1.0 wants grunt@>=0.4.0

Thank you.

**Comment by sindresorhus** [comment]
`>=0.4.0` matches `1.0.1` too. Try updating npm (I think it had some semver bug about this). If I bump it, it will be incompatible with people still using `0.4.0`.

**Comment by YaManicKill** [comment]
Ah yes, travis was using the bundled version of npm with node 4, so I've got it to install the newest version. Need to wait for that to go in, and then I'll be able to see if it fixes it, but thanks for that.
