### ISSUE TITLE
Support the ESLint `fix` option

### ISSUE THREAD

**Issue by EvtK** [sindresorhus/grunt-eslint#122]
Similiar has been requested here (a few days ago):

https://stackoverflow.com/questions/37132917/grunt-eslint-enabling-fix-flag-to-auto-fix-violations.

Have searched on the net, but couldn't find a package that is able to do this. Since the --fix option is already implemented in ESlint, I think it should be possible to attach this to the grunt task.

Care to take a look? Many thanks!

**Comment by kevva** [comment]
https://github.com/sindresorhus/grunt-eslint/issues/117
