### ISSUE TITLE
ES2015ify broke old node version builds

### ISSUE THREAD

**Issue by sagiegurari** [sindresorhus/grunt-eslint#125]
I have modules that support 0.10 and 0.12 but your change to use ecma 6 means I can't use your grunt task in travis builds that run my module against older node versions to ensure they work good.

**Comment by sindresorhus** [comment]
Read the ESLint release notes: http://eslint.org/blog/2016/07/eslint-v3.0.0-released

They now require Node.js 4.

**Comment by sagiegurari** [comment]
oh. that is not great.
anyway i worked around it by checking the nodejs version and based on that i decide if to force the eslint task via grunt-force-task.
its not a great workaround, but thats best i can do i guess.
