### ISSUE TITLE
Errors after Es2015ify

### ISSUE THREAD

**Issue by corneadoug** [sindresorhus/grunt-eslint#126]
I get errors and can't run grunt-eslint after [that commit](https://github.com/sindresorhus/grunt-eslint/commit/d0ff94266c668a5d6ad2bfd5bb0e92445f6a580a).
Is there additional configuration to do on grunt side to support es2015?

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/grunt-eslint/issues/125.
