### ISSUE TITLE
Please include loadNpmTasks("grunt-eslint") to the config

### ISSUE THREAD

**Issue by rohdef** [sindresorhus/grunt-eslint#134]
Hi,

We recently refactored our grunt setup to a shared project, to unify our build setup and ease the maintenance. During that change grunt started giving the following error:

    Warning: Task "eslint" not found.

Turns our that the following line was missing from our gruntfile (I am not sure why it even works in a local project):

    grunt.loadNpmTasks("grunt-eslint");

I think it would be a good idea to instruct people to insert it on the guide even though it's seemingly not needed if it's for a single project. That would also make your documentation more consistent with other grunt modules, which is always nice for us users. After all it is way easier to read and use documentation if you know what to expect :)

**Comment by sindresorhus** [comment]
It's not needed. That's what the `require('load-grunt-tasks')(grunt);` line does.
