### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by kevindb** [sindresorhus/grunt-eslint#146]
Would you please consider using semantic versioning for grunt-eslint?
With your current release pattern, you are iterating the _major_ version (the first number) with every release. In npm terminology, this indicates that you're making breaking changes, and that the new version is not backward compatible with previous versions of the package.

Instead, you could iterate the _minor_ version (the second number) when you're adding new features, but none of the existing functionality is breaking.

More information:
[Semantic versioning and npm](https://docs.npmjs.com/getting-started/semantic-versioning)
[Semantic Versioning](http://semver.org/)

Thank you

**Comment by sindresorhus** [comment]
I am using semantic versioning. Please look closer. It was a major release because ESLint was bumped from 3 to 4.
