### ISSUE TITLE
support eslint 7?

### ISSUE THREAD

**Issue by bonesoul** [sindresorhus/grunt-eslint#168]

**Comment by jdforrester** [comment]
It does? As of #167 which shipped in 23.0.0.

**Comment by bonesoul** [comment]
es2021 was introduced in ESLint version 7.8.0.

can we update the requirement to 7.8.0?

**Comment by bonesoul** [comment]
if anyone hits the error;

`Environment key "es2021" is unknown `

you can use my fork  until the PR gets merged:

` "grunt-eslint": "git+https://github.com/bonesoul/grunt-eslint.git",`
