### ISSUE TITLE
[Feature Request] Implement flat config compatibility

### ISSUE THREAD

**Issue by thakyZ** [sindresorhus/grunt-eslint#173]
I would love to see the ability to implement flat configuration as a suppliable eslint config.

**Comment by prantlf** [comment]
The support has landed in `25.0.0`. Thanks a lot, Sindre!

The flatconfig enabled by default wasn't the only change in ESLint 9. There're also changes in the API. Even if you fix the configuration, you still may not be able to upgrade, if some of your ESLint plugins aren't compatible with ESLint 9 yet.
