### ISSUE TITLE
Linting ignored files triggers a warning

### ISSUE THREAD

**Issue by mzgol** [sindresorhus/grunt-eslint#22]
See https://github.com/eslint/eslint/issues/905 for the description of the problem & discussion around it.

Basically, if you want to have filest passed to the `eslint` task usable for usage with `grunt-newer`, you need to pass files, not directories. But if you pass files and some of them are in `.eslintignore`, ESLint triggers a warning. This can seriously flood the console with warnings not applicable here; it's enough to e.g. pass `app/**/*.js` to the `eslint` task and have `app/vendor/**` in `.eslintignore`.

@nzakas proposed to add the `--silent` option to ignore warnings which would make this issue disappear but would also make all other warnings disappear.

Do you have a better idea how to solve this problem? Input welcome!

**Comment by pigulla** [comment]
Any updates on this?

**Comment by nzakas** [comment]
The API has been available in ESLint for a while now.  http://eslint.org/docs/developer-guide/nodejs-api.html

**Comment by sindresorhus** [comment]
@pigulla https://github.com/sindresorhus/grunt-eslint/issues/34#issuecomment-71067837

**Comment by ratherblue** [comment]
Did a flag for this specific functionality ever get added? gulp-eslint has `warnFileIgnored` but I didn't see a similar option for grunt-eslint. The ignored files are still showing up as warnings when I test this
