### ISSUE TITLE
Allow specifying different sets of options

### ISSUE THREAD

**Issue by Skalman** [sindresorhus/grunt-eslint#25]
I'd like to be able to specify one set of rules for my browser JS files and another for my Node JS files.

Basically, I'd like this to work:

``` js
initConfig = {
  eslint: {
    options: { config: 'conf/general-eslint.json' },
    browser_stuff: {
      options: { config: 'conf/browser-specific-eslint.json' },
      target: grunt.file.expand(['js/*.js']),
    },
    node_stuff: {
      options: { config: 'conf/node-specific-eslint.json' },
      target: ['Gruntfile.js']
    }
  }
};
```

As a general note, you should consider making the `grunt-eslint` very similar to the `grunt-contrib-jshint` API. A few things missing:
- My suggestion above
- Set options as an object rather than a file path
- Automatically glob file names (i.e. `grunt.file.expand`)

**Comment by mherodev** [comment]
Why do the docs say `src`?

**Comment by TimHeap46** [comment]
can you confirm please if we should be using src or target, as currently I can't get it to find any files to lint ?
