### ISSUE TITLE
opts.outputFile feedback

### ISSUE THREAD

**Issue by PabloDeGrote** [sindresorhus/grunt-eslint#45]
Hi,

Thanks for the great plugin! I have one small issue, I miss feedback if you use an outputFile.

I made a quick fix by adding this function:
````
function getErrorsAndWarnings(results, outputFile) {
	var errors = [],
		warnings = [];

	results.some(function (result) {
		result.messages.some(function (message) {
			if(message.severity === 2) {
				errors.push(message);
			} else if(message.severity === 1) {
				warnings.push(message);
			}
		});
	});

	if(warnings.length > 0 || errors.length > 0) {
		return chalk.yellow('eslint: Wrote ' + errors.length + ' errors and ' + warnings.length + ' warnings to ' + outputFile + '.');
	} else {
		return chalk.green('eslint: success without errors.');
	}
}
````

and then ofcourse adding the call ``grunt.log.writeln(getErrorsAndWarnings(results, opts.outputFile));`` within ``if (opts.outputFile) {``

I can add a pull request if needed.

**Comment by sindresorhus** [comment]
What do you mean "you miss feedback"? The whole point of outputting to a file is that you don't want it in the console but in a file.

**Comment by PabloDeGrote** [comment]
Yes, I don't want all the errors and warnings in my console, but I do like to have instant (summary) feedback of what ESlint did, not just a silent write to a file.

This is especially handy if you're working with more then one on a team and if new project members try to grunt they don't need to figure out the hard way why Grunt failed.

**Comment by sindresorhus** [comment]
@idok thoughts?

**Comment by sindresorhus** [comment]
@nzakas What do you think about CLIEngine returning how many errors and warnings there were so every consumer don't have to reimplement the above? I can open an issue on ESLint if wanted.

```js
var results = engine.executeOnFiles(this.filesSrc);
results.errorCount;
results.warningCount;
```

**Comment by idok** [comment]
The behaviour in grunt-eslint until version 5.0.0 and in other grunt tasks that I've worked with is that when you specify output file, all output goes to the file.
Usually this is used when the build is triggered by a machine and not a person (e.g. CI machine) and the output is parsed by another tool.
In the project I work on, the developers run eslint:all and the CI machine runs eslint:teamcity, the gruntfile.js looks like this:

```javascript
eslint: {
            all: {
                src: ['**/*.js']
            },
            teamcity: {
                options: {
                    format: 'checkstyle',
                    outputFile: 'target/eslint.xml'
                },
                src: ['<%= eslint.all.src %>']
            }
        }
```

Therefore, I think writing output to console when output file is configured is probably wrong.

**Comment by nzakas** [comment]
:+1: can you file an issue for that?

**Comment by PabloDeGrote** [comment]
@idok, Sorry my ticket was not very clear, we don't want to write the output to the console (only a small feedback line like they do in JSHint, i.e: 'Report jshint.log created.')

For the JSHint code see: https://github.com/gruntjs/grunt-contrib-jshint/blob/master/tasks/jshint.js#L74
