### ISSUE TITLE
"quiet" option does not work anymore

### ISSUE THREAD

**Issue by matz3** [sindresorhus/grunt-eslint#48]
Since this task is using the CLIEngine, the "quiet" option has not effect anymore.
Would be great if this task filters out the warnings like the CLI in eslint does.

I can also provide a PR if welcome.

**Comment by sindresorhus** [comment]
Open a ticket on ESLint about adding that to CLIEngine ;)

**Comment by matz3** [comment]
Feature was refused to add to CLIEngine (see referenced issue).
Any chance to get it added to this plugin?

**Comment by sindresorhus** [comment]
Sure
