### ISSUE TITLE
grunt throws js error when linting has errors, 5.1.0 grunt 0.4.5

### ISSUE THREAD

**Issue by gotofritz** [sindresorhus/grunt-eslint#49]
Hi. Thanks for the free tool. Since I've upgraded to 5.1.0 and using grunt 0.4.5, I get this javascript error on errors

![eslint-error](https://cloud.githubusercontent.com/assets/604900/6066865/a5a5f6b4-ad70-11e4-9a42-1c1f6821b6e9.png)

Warnings and success are still fine

![eslint-warnings](https://cloud.githubusercontent.com/assets/604900/6066881/c01814f0-ad70-11e4-9d2b-9f583fa18558.png)

Thanks in advance

**Comment by sindresorhus** [comment]
Yes, that's as intended. It fails if ESLint has a "problem" to get the correct exit code.
