### ISSUE TITLE
Multiple configuration / targets

### ISSUE THREAD

**Issue by elmasse** [sindresorhus/grunt-eslint#51]
Hello, this is more a question rather than an issue. Is it possible to run eslint in multiple targets with different config?

Something like this:

```
eslint: {
   source: {target: ['src/*.js'], envs: ['node']},
   tests: {target: ['tests/*.js'], envs: ['node', 'mocha']},
}

```

**Comment by elmasse** [comment]
Never mind. It is easier to have a .eslintrc with different props inside the test folder and add it to the targets array. Closing the issue now.

**Comment by mato75** [comment]
How did you set .eslintrc configFile?
