### ISSUE TITLE
Support multiple targets

### ISSUE THREAD

**Issue by davidjgoss** [sindresorhus/grunt-eslint#53]
It would be great to be able to have multiple eslint targets, like this:

``` javascript
eslint: {
    standard: {
        options: {
            configFile: "bower_components/eslintconfigs/standard.json"
        },
        target: [
            "Gruntfile.js",
            "src/**/*.js",
            "!src/**/nls/**/*.js"
        ]
    },
    tests: {
        options: {
            configFile: "bower_components/eslintconfigs/jasmine.json"
        },
        target: ["tests/**/*.js"]
    },
    nls: {
        options: {
            configFile: "bower_components/eslintconfigs/legacy-nls.json"
        },
        target: ["src/**/nls/**/*.js"]
    }
}
```

Currently if you try to do this, grunt knows what you mean but grunt-eslint doesn't:

![image](https://cloud.githubusercontent.com/assets/3192745/6484061/35ae29b6-c270-11e4-8ede-4ed73c140e12.png)

For example, [grunt-csslint has the functionality](https://www.npmjs.com/package/grunt-contrib-csslint#usage-examples).

(Am aware I could achieve the desired outcome by adding `.eslintc` files to the various directories, but this setup would work a lot better in many cases, especially where we have a master set of configs being used for dozens of projects and pulled in via Bower or Maven.)

Happy to do a PR, but wanted to check if there were reasons not to do it first.

**Comment by sindresorhus** [comment]
You're using the wrong config. Nothing specific to this task. Read the grunt docs.

```js
eslint: {
    standard: {
        options: {
            configFile: "bower_components/eslintconfigs/standard.json"
        },
        src: [
            "Gruntfile.js",
            "src/**/*.js",
            "!src/**/nls/**/*.js"
        ]
    },
    tests: {
        options: {
            configFile: "bower_components/eslintconfigs/jasmine.json"
        },
        src: ["tests/**/*.js"]
    },
    nls: {
        options: {
            configFile: "bower_components/eslintconfigs/legacy-nls.json"
        },
        src: ["src/**/nls/**/*.js"]
    }
}
```

**Comment by davidjgoss** [comment]
Oh hell, you're right, sorry about that. Think I got mixed up with the README.md examples using `target: []` not `src: []`. Appreciate the super-quick response, thanks.
