### ISSUE TITLE
Options for disabling all rules by default

### ISSUE THREAD

**Issue by ptitgraig** [sindresorhus/grunt-eslint#54]
Hello.
First, thanks for this great plugin.

This issue could be labelled as a question. 
I'm wondering if adding an option to reset all rules could be a good idea ?

Eslint has the `--reset` cli option for this use-case.

Regards.

**Comment by sindresorhus** [comment]
I guess.

@nzakas Thoughts?

**Comment by nzakas** [comment]
It's already exposed in `CLIEngine` as an option.

**Comment by sindresorhus** [comment]
Ok, http://eslint.org/docs/developer-guide/nodejs-api#cliengine
