### ISSUE TITLE
Support command line option "format"

### ISSUE THREAD

**Issue by rsternagel** [sindresorhus/grunt-eslint#60]
I'm not sure what the grunt plugin convention (for passing through options) is but for the following line I would expect that the plugin uses the tap format.

`$ grunt eslint --format=tap`

My use case is a remote-controlled Gruntfile, so changing the Gruntfile itself is unfortunately no option.

This is hacky workaround for `tasks/eslint.js`:
```javascript
...
  grunt.registerMultiTask('eslint', 'Validate files with ESLint', function () {
      var opts = this.options({
        outputFile: false,
        quiet: false
      });

      // new code
      if (grunt.option('format')) {
        opts.format = grunt.option('format');
      }

      ...
```

**Comment by sindresorhus** [comment]
No thanks
