### ISSUE TITLE
Can't find way to enable --no-eslintignore rule

### ISSUE THREAD

**Issue by globexdesigns** [sindresorhus/grunt-eslint#63]
How can I enable the `--no-eslintignore` rule when running grunt-eslint? I tried putting it in "options" but that didn't work.

**Comment by kevva** [comment]
Set `ignore` to `false`.

**Comment by globexdesigns** [comment]
That's not right. `ignore: false` will disable the use of the `eslintignore` file completely. I just want to disable the warning that are shown when that file is used.

**Comment by sindresorhus** [comment]
@globexdesigns Yup, but this plugin supports any options the ESLint CLIEngine supports (not the CLI). Ask on the ESLint issue tracker to get it added the to CLIEngine ;)

https://github.com/eslint/eslint/issues/new

**Comment by kevva** [comment]
@globexdesigns, ah, sorry, my mistake.
