### ISSUE TITLE
different

### ISSUE THREAD

**Issue by ChrisPiechowicz** [sindresorhus/grunt-eslint#64]
Is it possible to set different rules for each set of files? For example a set of rules for node, then for browser js etc. I've tried this:

        eslint: {
            node: {
                options: {
                    envs: ['node'],
                    rules: {
                        quotes: [0, 'double'],
                        strict: 0
                    }
                },
                target: [
                    'src/app.js'
                ]
            },
            browser: {
                options: {
                    envs: ['browser'],
                    rules: {
                      .....
                    }
                },
                target: [
                     .....
                ]                
            }
        }

But it doesn't find files to validate.

**Comment by sindresorhus** [comment]
I think you're missing how the grunt config object works. Nothing unique to this task.

https://github.com/sindresorhus/grunt-eslint/issues/53
