### ISSUE TITLE
"env" vs "envs"

### ISSUE THREAD

**Issue by cecchi** [sindresorhus/grunt-eslint#71]
The API eslint exposes is not identical to the command line API or however it parses `.eslintrc` configs. In order to get the `env` option to work you must instead use `envs` and pass an array instead of an object literal.

What's documented at eslint.org:
```js
{
    'env' : {
        'browser' : true,
        'node' : true
    }
}
```

What's required using grunt-eslint:
```js
{
    'env' : [
        'browser',
        'node'
    ]
}
```

For some context, I asked and apparently eslint used to support both `env` and `envs`. It seems like a bug - or just poor design - on their end, but at the very least we should document this in the README.

**Comment by sindresorhus** [comment]
This task just refers to the ESLint docs. If anything is unclear about any ESLint option, it should be improved there, not here. http://eslint.org/docs/developer-guide/nodejs-api#cliengine
