### ISSUE TITLE
Can't get grunt-eslint to work with grunt-contrib-watch (watch only changed files)

### ISSUE THREAD

**Issue by sevagsim** [sindresorhus/grunt-eslint#72]
Can't get grunt-eslint to work with grunt-contrib-watch (watch only changed files)

Thoughts on how to accomplish this with grunt-contrib-watch?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gruntjs
Paste in the link to the question here so others can follow ;)

**Comment by aaronjensen** [comment]
apparently the question is here: http://stackoverflow.com/questions/31094037/grunt-contrib-watch-does-not-work-with-eslint-to-watch-only-changed-file-sets

no answer yet, though

**Comment by david-zacharias** [comment]
:+1: Would be nice to have this working.
