### ISSUE TITLE
envs doesn't work correctly

### ISSUE THREAD

**Issue by sazzer** [sindresorhus/grunt-eslint#73]
I'm trying to set up ESLint from my Grunt setup, so that when I lint all of my main code it uses a particular config file, and when I lint my test code it does exactly the same but adds the 'mocha' environment. 

The way to do this with eslint itself is easy - you just add '--env mocha' to the command line and everything else just works.

The grunt-eslint documentation seems to imply that I can do this by adding
```
envs: ['mocha']
```
to the options for this step. This doesn't work however.

I think the problem is that the file tasks/lib/eslint.js doesn't handle this setting properly. Adding this to that file seems to make it work, but I'm not sure if there's just another way that it's handled?
```
    if (options.envs) {
      args.push("--env", options.envs.join(","));
    }
```

**Comment by sindresorhus** [comment]
This task just passes the option directly to ESLint. https://github.com/sindresorhus/grunt-eslint/blob/259e01e8f3725475b27957da08da69b1bc655ea4/tasks/eslint.js#L46

You should probably open this on the ESLint issue tracker instead ;)

**Comment by sazzer** [comment]
It doesn't though. I added some console.log commands to both this file and the ESLint lib/cli.js file, and the options don't come through.

**Comment by sindresorhus** [comment]
Then your gruntfile config is probably wrong. Looks at the examples in the readme.

**Comment by sazzer** [comment]
Sorry - it's worse than that actually!

I'd been using "eslint-grunt" in my app, not "grunt-eslint". Switched to this one and it all works exactly as expected.

**Comment by sindresorhus** [comment]
Haha, no worries :)

**Comment by arthurvr** [comment]
We should probably discuss if it's really needed to have two tasks that seem to do the same thing. https://github.com/iancmyers/eslint-grunt/issues/8.

**Comment by sazzer** [comment]
I think that's just the perils of the open source world. Two different people decided to write two different plugins that do essentially the same thing, and pick names that are very similar. There's going to be a bit of confusion there, which can't easily be avoided. End of the day, it all works so I'm happy.
