### ISSUE TITLE
Semver compliance

### ISSUE THREAD

**Issue by davidnormo** [sindresorhus/grunt-eslint#74]
Can you stick to semver for versioning? For example updating the eslint dependency from `0.23.0 -> 0.24.0` is not a breaking change, should be a patch number increment `15.0.1` not `16.0.0`

Thanks

**Comment by sindresorhus** [comment]
Yes it is. Read semver again. Anything pre-1.0 can be breaking. Yes, it was a mistake to 1.0.0 this one before ESLint, but that's what happened. And ESLint does actually break stuff in every minor release.
