### ISSUE TITLE
.eslintignore not working

### ISSUE THREAD

**Issue by JulianLaval** [sindresorhus/grunt-eslint#79]
I'm having trouble getting `grunt-eslint` to pick up an `.eslintignore` file.

My setup is rather atypical in that I'm running the task on files in sibling directories rather than in the working directory itself.

```
grunt.initConfig({
    eslint: {
      options: {
        configFile: '.eslintrc',
        extensions: ['.js', '.html', '.xhtml', '.htm']
      },
      one: ['../' + project],
      all: ['../*']
    },
});
```

This doesn't seem to pick up any `.eslintignore` files, regardless of whether in the working directory, parent directory, or directory being tested. Adding it as an `ignorePath` option doesn't work either.

Is this a known issue or am I just being thick?

**Comment by sindresorhus** [comment]
This task just [passes](https://github.com/sindresorhus/grunt-eslint/blob/110c4a9acd319ead863b18d6a00976336811ee26/tasks/eslint.js#L33) your options to ESLint. Better ask on StackOverflow or open an issue on ESLint.

**Comment by JulianLaval** [comment]
Noted, thanks!

**Comment by JulianLaval** [comment]
Issue solved.

For reference: http://stackoverflow.com/questions/32184532/eslintignore-not-working-in-sibling-directory
