### ISSUE TITLE
Convert output from ANSI to HTML

### ISSUE THREAD

**Issue by JulianLaval** [sindresorhus/grunt-eslint#80]
As it stands, it seems that the `outputFile` option simply pipes the ANSI report to the file specified. I'm wondering whether it would make sense to natively convert the report to a more user-friendly format such as HTML? Would this warrant inclusion or should it be up to the end-user to convert this themselves?

**Comment by sindresorhus** [comment]
ESLint now has a JSON reporter, so I think we should just dump using that instead. JSON is easy to parse.

**Comment by JulianLaval** [comment]
Ah yes, completely missed the `format` option. Maybe worth looking into submitting a HTML formatter PR to ESLint itself rather than Grunt ESLint - will keep you posted.

**Comment by JulianLaval** [comment]
For reference, a HTML formatter was added in ESLint [v1.3.0](https://github.com/eslint/eslint/releases/tag/v1.3.0) :)
