### ISSUE TITLE
Uses global eslint version when installed

### ISSUE THREAD

**Issue by tilmanpotthof** [sindresorhus/grunt-eslint#83]
I had a global version of eslint installed (1.1.0) and everything worked fine, but the CI job failed with the "eqeqeq" rule. I could not reproduce this error locally until I updated my global eslint version to 1.4.1.

This behavior is quite confusing, because you don't expect that local node_modules with their own dependencies depend on global version.

**Comment by sindresorhus** [comment]
It does not depend on a global ESLint. Must be something wrong with your setup.

https://github.com/sindresorhus/grunt-eslint/blob/110c4a9acd319ead863b18d6a00976336811ee26/package.json#L33

**Comment by tilmanpotthof** [comment]
Seems to be a default behavior of npm. I could reproduce the problem with an explicit eslint dependency.

**Comment by tilmanpotthof** [comment]
Thanks for the quick response!
