### ISSUE TITLE
Looks like the fix option is not working

### ISSUE THREAD

**Issue by oliviertassinari** [sindresorhus/grunt-eslint#86]
I can't make the [fix option](http://eslint.org/docs/developer-guide/nodejs-api) work.

- Running the task with this config on my files ouputs 4 errors.
``` js
options: {},
```

 - But running this output 0 error and my files aren't edited.
``` js
options: {
   fix: true
},
```

**Comment by sindresorhus** [comment]
Yeah, it hasn't been implemented yet. I don't have the time to look at it right now, so PR welcome.
