### ISSUE TITLE
Unknown node type ExportDefaultDeclaration when linting ES6 modules

### ISSUE THREAD

**Issue by Enet4** [sindresorhus/grunt-eslint#88]
I've recently become unable to use this grunt task because it fails to understand `export default` statements in my files.

Calling the latest version of `eslint` (1.6.0) on the CLI works fine:

    eslint -c .eslintrc src/*.js src/*.jsx Gruntfile.js

However, when using version 17.2.0 of this task (also using `eslint` 1.6.0):

```javascript
    eslint: {
      gruntfile: 'Gruntfile.js',
      all: [ 'src/*.js', 'src/*.jsx' ]
    },
```

And this .eslintrc:

```json
{
  "ecmaFeatures": {
    "modules": true,
    "jsx": true
  },
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true
  },
  "plugins": [
    "react"
  ],
  "rules": {
    "no-alert": 0,
    "no-console": 0,
    "quotes": 0,
    "curly": 0,
    "global-strict": 0,
    "new-cap": 0,
    "no-unused-vars": 0,
    "comma-spacing": 0,
    "space-infix-ops": 0,
    "no-trailing-spaces": 0,
    "camelcase": 1,
    "comma-dangle": 1,
    "no-mixed-spaces-and-tabs": 1,
    "no-multi-spaces": 1,
    "no-extra-semi": 1,
    "key-spacing": 1,
    "semi-spacing": 1,
    "eol-last": 1
  }
}
```

The outcome is this:

 > Running "eslint:gruntfile" (eslint) task
 > 
 > Running "eslint:all" (eslint) task
 > Warning: Unknown node type ExportDefaultDeclaration. Use --force to continue.
Error: Unknown node type ExportDefaultDeclaration.
    at Controller.traverse (.../node_modules/estraverse/estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (.../node_modules/eslint/lib/eslint.js:779:24)
    at processText (.../node_modules/eslint/lib/cli-engine.js:221:27)
    at processFile (.../node_modules/eslint/lib/cli-engine.js:258:18)
    at executeOnFile (.../node_modules/eslint/lib/cli-engine.js:604:23)
    at .../node_modules/eslint/lib/cli-engine.js:628:17
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (.../node_modules/eslint/lib/cli-engine.js:626:18)
    at Object.<anonymous> (.../node_modules/grunt-eslint/tasks/eslint.js:37:20)
    at Object.<anonymous> (.../node_modules/grunt/lib/grunt/task.js:264:15)

I'm not sure, but could it be a conflict with the `estraverse` dependency?

```
$ npm list estraverse --depth 9
my-package@0.1.0 ...
+-- eslint@1.6.0
| +-- escope@3.2.0
| | +-- esrecurse@3.1.1
| | | `-- estraverse@3.1.0 
| | `-- estraverse@3.1.0 
| `-- estraverse@4.1.0 
`-- grunt-browserify@4.0.1
  `-- browserify@11.2.0
    `-- module-deps@3.9.1
      `-- detective@4.2.0
        `-- escodegen@1.7.0
          `-- estraverse@1.9.3 
```

**Comment by sindresorhus** [comment]
https://github.com/eslint/eslint/issues/new

**Comment by Enet4** [comment]
Again, I stated that using `eslint` directly does no pose this issue, so there was clearly something less obvious happening here. Calling it a problem with ESLint was a hasty move. In fact, I found out that the real problem isn't on `eslint`'s side at all ([npm/#9708](https://github.com/npm/npm/issues/9708) and [npm/#9663](https://github.com/npm/npm/issues/9663) explain the issue further).

Anyway, installing `estraverse@4.0.1` as a devDependency in my project solved my problem.
