### ISSUE TITLE
Support for max-warnings

### ISSUE THREAD

**Issue by pmcelhaney** [sindresorhus/grunt-eslint#90]
Is there a specify [max-warnings](https://github.com/eslint/eslint/pull/3580) (which is an option in the CLI)?

**Comment by sindresorhus** [comment]
The plugin uses the ESLint [CLIEngine](http://eslint.org/docs/developer-guide/nodejs-api#cliengine). You could ask on the ESLint issue tracker to have it added there too.

**Comment by pmcelhaney** [comment]
FYI, the ESLint team has declined a request to modify CLIEngine to support this feature automagically. 

https://github.com/eslint/eslint/issues/4125
