### ISSUE TITLE
[proposal] Linting only modified files

### ISSUE THREAD

**Issue by ctomczyk** [sindresorhus/grunt-eslint#92]
Wouldn't be possible to linting only modified files using some additional option is options? I can imagine something like that:

1. Lint all files and write creation/modified date of file to cache (as a json string).
2. Lint again same files, but only those that has been modified from last time.

This would significantly speed up the lint process.

**Comment by sindresorhus** [comment]
You can already do this with the `cache` option. Please read the docs before opening an issue...

**Comment by ctomczyk** [comment]
My mistake. You're right.
