### ISSUE TITLE
Increase the min version of eslint package

### ISSUE THREAD

**Issue by OndrejBrejla** [sindresorhus/grunt-eslint#99]
Hi, can you increase the min eslint version to ^1.10.0? 1.5.1 is too old...and some rules doesn't work properly in it (e.g. "no-multiple-empty-lines" with maxEOF option, even though it should). And since we have a lot of developers in a team, they called npm install in different times and almost everyone has a different version of eslint and each of them behaves a bit differently :) Thanks for the answer!

**Comment by OndrejBrejla** [comment]
Or it would be better to use more strict version dependency. To not use any "caret" and "tilda" before the eslint version...so everyone has the same version for same grunt-eslint version...so every machine will produce the same results. Today it's very hard to use it in distributed development...as I said, every machine, different version of eslint for *same* version of grunt-eslint...and different results. Thanks a lot!

**Comment by sindresorhus** [comment]
Not something that should change here. This is how every npm package works. Use npm@3 and add the ESLint version you want and it will be deduplicated to the correct one, or just use shrinkwrap.

**Comment by OndrejBrejla** [comment]
Yep, I expected such an answer ;-) But you can still at least update eslint version to ^1.10.0, can't you? :-) Thanks a lot.

**Comment by sindresorhus** [comment]
No, there's no reason to.
